version: 2.1

rspec_chrome_job: &rspec_chrome_job
  steps:
    - browser-tools/install-chrome
    - checkout
    - run:
        command: gem install bundler:2.2.3 && bundle install
    - run:
        name: rspec
        command: |
          DEBUG=1 bundle exec rspec --profile 10 \
            --format RspecJunitFormatter \
            --out test_results/rspec.xml \
            --format documentation

jobs:
  rspec_chrome_ruby2_6:
    docker:
      - image: cimg/ruby:2.6.7-browsers
    <<: *rspec_chrome_job

  rspec_chrome_ruby2_7:
    docker:
      - image: cimg/ruby:2.7.4-browsers
    <<: *rspec_chrome_job

  rspec_chrome_ruby3_0:
    docker:
      - image: cimg/ruby:3.0.0-browsers
    <<: *rspec_chrome_job

  rspec_firefox:
    docker:
      - image: cimg/ruby:2.7.4-browsers
    steps:
      - checkout
      - run:
          command: gem install bundler:2.2.3 && bundle install
      - run:
          name: install firefox-nightly
          command: |
            wget -O nightly.tar.bz2 "https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US"
            tar xf nightly.tar.bz2
      - run:
          name: rspec
          command: |
            DEBUG=1 PUPPETEER_PRODUCT_RSPEC=firefox \
            PUPPETEER_EXECUTABLE_PATH_RSPEC=${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/firefox/firefox \
            bundle exec rspec --profile 10 \
              --failure-exit-code 0 \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format documentation spec/integration/
      - run:
          name: rspec (retry)
          command: |
            DEBUG=1 PUPPETEER_PRODUCT_RSPEC=firefox \
            PUPPETEER_EXECUTABLE_PATH_RSPEC=${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/firefox/firefox \
            bundle exec rspec --only-failures --format documentation spec/integration/

  rspec_firefox_pending_check:
    docker:
      - image: cimg/ruby:2.7.4-browsers
    steps:
      - checkout
      - run:
          command: gem install bundler:2.2.3 && bundle install
      - run:
          name: install firefox-nightly
          command: |
            wget -O nightly.tar.bz2 "https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US"
            tar xf nightly.tar.bz2
      - run:
          name: rspec
          command: |
            DEBUG=1 PUPPETEER_PRODUCT_RSPEC=firefox PENDING_CHECK=true \
            PUPPETEER_EXECUTABLE_PATH_RSPEC=${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/firefox/firefox \
            bundle exec rspec --profile 10 \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format documentation spec/integration/

orbs:
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  ci:
    jobs:
      - rspec_chrome_ruby2_6
      - rspec_chrome_ruby2_7
      - rspec_chrome_ruby3_0
      - rspec_firefox
      - rspec_firefox_pending_check
