name: Check

on: [pull_request]

jobs:
  check:
    name: documents updated
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - run: |
        bundle exec ruby development/generate_api_coverage.rb
        git diff --exit-code
